### PR TITLE
Add cluster role bindings for the deletion namespace

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards [#2296](https://github.com/giantswarm/giantswarm/issues/2296)

Add cluster role bindings for the service account created when a guest cluster is about be deleted

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I see lots of PRs now adding stuff to legacy resources. We also have to move forward with this and provide regular dedicated resources for all things we add.

**Comment by pipo02mix** [comment]
Let me explain you. I have split this [PR](https://github.com/giantswarm/flannel-operator/pull/101) into smaller ones, so you can review better the changes. Same as I did with KVM operator but I hope now the slices are better chosen. 

Since I would like to finish this RBAC epic ASAP, imo I go first with legacy (that is the working one IIRC) and the I will work in the new version with dedicates resources. I have update this [ticket](https://github.com/giantswarm/giantswarm/issues/1975) 

BTW I leave the big PR there just for testing purposes

**Comment by xh3b4sd** [comment]
This PR has conflicts.

**Comment by pipo02mix** [comment]
Solved PTAL

**Pull request merged**
