### PR TITLE
removes k8s health endpoint

### PR DESCRIPTION
**Pull request by xh3b4sd**

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
LGTM, might want to test this manually because no e2e tests. Depends on how confident you are.

**Review by tuommaki — APPROVED** [review]

**Comment by xh3b4sd** [comment]
Tested on `geckon`. There was one worker not coming up which does not seem to be related to this PR. /cc @calvix FYI. Lets maybe create a PM for the situation on `geckon` in case that makes sense. Let me know when I should collect any information.

**Review by calvix — APPROVED** [review]

**Comment by calvix** [comment]
@xh3b4sd it was probably my fault when I had some leftovers on one fo the worker node from testing flatcar instead of coreos.

**Comment by xh3b4sd** [comment]
I will then go ahead and merge here. 

@calvix did you cleanup on `geckon`? Did the cluster recover after the cleanup? I think it should and if not we should have a PM to improve on the resiliency there.

**Comment by calvix** [comment]
> @calvix did you cleanup on geckon? Did the cluster recover after the cleanup? I think it should and if not we should have a PM to improve on the resiliency there.

yes after cleanup the second worker joined cluster

**Comment by xh3b4sd** [comment]
Awesome. Thanks man. 🎉

**Pull request merged**
