### PR TITLE
set-namespaces-to-value

### PR DESCRIPTION
**Pull request by calvix**
remove hardcoded namespace

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
This should be fine. I am unsure if there is maybe a better way to do this.

**Review by fgimenez — APPROVED** [review]
LGTM

**Review by TheoBrigitte — COMMENTED** [review]
Would this work without updating other template namespace ?
e.g. configmap 
https://github.com/giantswarm/flannel-operator/blob/74c36b37c17bcf9f306b59254995c501b4142232/helm/flannel-operator-chart/templates/configmap.yaml#L5

**Comment by calvix** [comment]
@TheoBrigitte you are right, i forget about that :( thanks!

**Pull request merged**
