### PR TITLE
Add service account

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards [#2296](https://github.com/giantswarm/giantswarm/issues/2296)

Add service account for every network namespace created by flannel.

(Split part of https://github.com/giantswarm/giantswarm/issues/1975)

### CODE REVIEW

**Comment by pipo02mix** [comment]
I have thought when they are in a namespace, it would be deleted at the namespace deletion. Am I wrong?

**Comment by xh3b4sd** [comment]
You are right the namespace usually should just clean everything inside of it. So far we implemented the resources properly though and I would like to keep this for correctness. I can totally see Kubernetes internals being changed and our resources should just do their job properly regardless.

**Comment by pipo02mix** [comment]
I have done what you suggested but I have realized that daemonset (flannel network) have not delete action

**Comment by xh3b4sd** [comment]
Disappointing. Then lets just do it somehow.

**Comment by pipo02mix** [comment]
But do you want me to implement it here? I think to create a new PR is better

**Comment by xh3b4sd** [comment]
No just make it work somehow. I was under the impression it does already work because the namespace takes everything down implicitly. Lets not overdo it now but rather iterate on it every week. Then we can make progress now and reduce the technical debt over time. It hurts me but it is better for the company now.

**Comment by pipo02mix** [comment]
Yes, it works because daemon set is deleted when the namespace is removed. I like the idea to iterate over it. I do like to work on it since now I know slightly how it works so not sure if the best way is joining SIG operator and take some time every week for it. WDYT?

BTW you can approve it or there is something else to take care here?

**Comment by xh3b4sd** [comment]
> not sure if the best way is joining SIG operator and take some time every week for it

When this matches your interest go for it. More hands are appreciated.

**Pull request merged**
