### PR TITLE
add cluster role bindings resource structure

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://gigantic.slack.com/archives/C2MS2VB37/p1556182616007900.

### CODE REVIEW

**Comment by kopiczko** [comment]
I'm uncertain if this is a good thing. We can talk about that tomorrow if you want.

**Comment by xh3b4sd** [comment]
When you have something to talk about we can hang.

**Comment by tuommaki** [comment]
For my interest: This is base for a resource to correctly maintain the role bindings lifecycle?

**Comment by xh3b4sd** [comment]
In the long run yes. For now my idea was to have this resource managing the proper deletion of cluster role binding leftovers. I try to address a PM. Pawel has concerns we need to talk about though.

**Review by tuommaki — APPROVED** [review]
I'm good with this.

**Comment by xh3b4sd** [comment]
The PM I worked on got sorted. This PR is still useful as we would like to have a resource for the cluster role binding management. The work being done here is a step into the right direction. We only have to add functionality later. Merging now.

**Pull request merged**
